version: '3.8'

services:
  estoqueapi:
    container_name: estoqueapi-container
    build:
      context: ./EstoqueApi
      dockerfile: Dockerfile
    ports:
      - "7039:80"  
    depends_on:
      - rabbitmq
  
  rabbitmq:
    container_name: rabbitmq-container
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"  
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5